env:
  es2021: true
  node: true
extends:
  - standard
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  space-before-function-paren: off
globals:
  prefix: writable
  color: readonly
  log: readonly